### ISSUE TITLE
Link Function

### ISSUE THREAD

**Issue by felipe-sartes** [rafamoral/hnp#1]
Usando o pacote em aulas de MLG tanto alunos (no caso eu) e Professor notamos que ao realizar um exemplo da apostila de Clarice e Demétrio o pacote hnp não trouxe um resultado satisfatório quanto aos códigos do professor Gilberto A. Paula, isso se deve ao fato do hnp ser codificado apenas as funções de ligação canônicas? Lendo o próprio artigo não ficou tão claro (para mim) se de fato é isso mesmo, pois na parte de exemplos estão apenas as canônicas que foram apresentadas no decorrer da disciplina e por mais útil e bem feito esteja o pacote me surgiu essa duvida. Grato pela formulação e aplicação desse pacote.

**Comment by rafamoral** [comment]
Oi Felipe, acabei de notar que não atualizei o repositório do GitHub. A versão atual do hnp está no CRAN. Essa versão lida com diferentes funções de ligação. Por favor, atualize por meio de

install.packages(“hnp”)

- Rafael
